defmodule Jido.Connect.Catalog.Manifest do
  @moduledoc """
  Package-level provider manifest derived from a compiled Jido Connect spec.

  This is the read-only discovery record for installed connector packages. It
  should be generated by `use Jido.Connect`, not manually authored.
  """

  alias Jido.Connect.ConnectorCapability
  alias Jido.Connect.Catalog.{AuthProfileSummary, Tool}

  @schema Zoi.struct(
            __MODULE__,
            %{
              id: Zoi.atom(),
              name: Zoi.string(),
              description: Zoi.string() |> Zoi.nullish() |> Zoi.optional(),
              app: Zoi.atom() |> Zoi.nullish() |> Zoi.optional(),
              package: Zoi.atom() |> Zoi.nullish() |> Zoi.optional(),
              module: Zoi.module(),
              version: Zoi.string() |> Zoi.nullish() |> Zoi.optional(),
              status: Zoi.atom() |> Zoi.default(:available),
              category: Zoi.atom() |> Zoi.nullish() |> Zoi.optional(),
              tags: Zoi.list(Zoi.atom()) |> Zoi.default([]),
              visibility: Zoi.atom() |> Zoi.default(:public),
              docs: Zoi.list(Zoi.string()) |> Zoi.default([]),
              capabilities: Zoi.list(ConnectorCapability.schema()) |> Zoi.default([]),
              auth_profiles: Zoi.list(AuthProfileSummary.schema()) |> Zoi.default([]),
              actions: Zoi.list(Tool.schema()) |> Zoi.default([]),
              triggers: Zoi.list(Tool.schema()) |> Zoi.default([]),
              generated_modules: Zoi.map() |> Zoi.default(%{}),
              metadata: Zoi.map() |> Zoi.default(%{})
            },
            coerce: true
          )

  @type t :: unquote(Zoi.type_spec(@schema))
  @enforce_keys Zoi.Struct.enforce_keys(@schema)
  defstruct Zoi.Struct.struct_fields(@schema)

  def schema, do: @schema
  def new!(attrs), do: Zoi.parse!(@schema, attrs)
  def new(attrs), do: Zoi.parse(@schema, attrs)
end
